### ISSUE TITLE
nemu 中的除法行为

### ISSUE THREAD

**Issue by jauzzz** [Googol2002/NJU-ICS2021-PA#1]
hello，抱歉通过 issue 联系你。

我最近也在进行 ics 2021 的 pa，riscv32 体系，在 pa1 表达式求值中遇到这样一个问题：

- gcc 中 10/-3 = -3
- nemu 中 10 / -3 = 0

关于负数的除法行为，我有找到一些相关解释：https://codeyarns.com/tech/2019-03-06-integer-division-in-c.html

就是想问问你是否也遇到这个情况（我clone你的仓库想运行试试，但是遇到 unknown type name ‘riscv32_CSR_state’，然后也不是南大学生），这个问题导致我的pa1一直会 fail 很多测试，卡挺久了所以冒昧来打扰你~

**Comment by Googol2002** [comment]
谢谢你对我项目的关注。

首先，在PA1的表达式求值任务中，10/-3=0是“正确”的答案（我的作业通过了JYY老师所有的OJ测评，因此这个问题并不会导致你Fail掉OJ）。我来解释一下为什么会这样，在PA1的表达式求值中，按照要求，我们将所有代数运算均按照无符号整数进行运算（这种要求是为了规避Undefined Behavior），因此会得到一些违反常识的结果。

在计算机中，负数使用补码进行表示，因此当你按照无符号整数运算求解 |a| / (-|b|) 时，其实对于计算机而言是在求解 |a| / (2^n - |b|) 。当我们带入你提到的输入可以得到：|10| / (2^32 - |-3|) = 0，从计算机的角度看，这是正确的。

带来这个反常识问题的关键在于我们引入了”将所有代数运算均按照无符号整数进行运算“这条假设。

你可以写一个对拍器来找到Bug，部分代码参考NEMU下的 tools/gen-expr。祝你BUG--，hhh

**Comment by jauzzz** [comment]
> 谢谢你对我项目的关注。
> 
> 首先，在 PA1 的表达式求值任务中，10/-3=0 是「正确」的答案（我的作业通过了 JYY 老师所有的 OJ 测评，因此这个问题并不会导致你 Fail 掉 OJ）。我来解释一下为什么会这样，在 PA1 的表达式求值中，按照要求，我们将所有代数运算均按照无符号整数进行运算（这种要求是为了规避 Undefined Behavior），因此会得到一些违反常识的结果。
> 
> 在计算机中，负数使用补码进行表示，因此当你按照无符号整数运算求解 |a| / (-|b|) 时，其实对于计算机而言是在求解 |a| / (2^n - |b|) 。当我们带入你提到的输入可以得到：|10| / (2^32 - |-3|) = 0，从计算机的角度看，这是正确的。
> 
> 带来这个反常识问题的关键在于我们引入了「将所有代数运算均按照无符号整数进行运算」这条假设。
> 
> 你可以写一个对拍器来找到 Bug，部分代码参考 NEMU 下的 tools/gen-expr。祝你 BUG--，hhh

感谢回复（ps：不好意思回晚了

那这么说的话，nemu 的除法指令是已经默认将操作数看成是 unsigned 类型了吗？（我做 10 / -3 时都是以 int 类型测试）

**Comment by Googol2002** [comment]
准确的说，只是在PA1的表达式求值部分是这样的。在实现div指令不可以这样理解。以上。
