### ISSUE TITLE
监视点求值部分check_watchpoint函数

### ISSUE THREAD

**Issue by hululu-lzb** [Googol2002/NJU-ICS2021-PA#2]
bool check_watchpoint(WP **point){
  WP *cur = head;
  bool success = true;
  while (cur){
    if (expr(cur->condation, &success)){
      *point = cur;
      //IFDEF(CONFIG_DEBUG, Log("Break"));
      return true;
    }
    cur = cur->next;
  }
  return false;
}

当在循环中使用expr函数计算时，只要表达式值不为0都会返回true,但监视点功能不是要值改变才有响应吗？感谢您的回复

**Comment by hululu-lzb** [comment]
#ifdef CONFIG_ITRACE
    WP* point = NULL;
    if (check_watchpoint(&point)){
      printf("Stoped at \e[1;36mWatchPoint(NO.%d)\e[0m: %s \n", point->NO, point->condation);
      puts(_this->logbuf);
      nemu_state.state = NEMU_STOP;
    }
  #endif

这是cpu执行函数中的部分，只要check_point函数返回true就中断。结合上面，只要表达式有值就会中断而不管值是否改变？

**Comment by Googol2002** [comment]
坦率地讲，距离我编写这段代码已经过去了一年半之久，我不确定我下面的解释是否严格准确。

从我使用IDE的经验来看，监视点功能是当Condition满足时（具体地，到达指定PC，并且，逻辑表达式满足），就会引发中断，与“值改变“没有什么联系。这个代码只是一种辅助工具，似乎对于项目的功能没有影响。

**Comment by hululu-lzb** [comment]
嗯，IDE中的确是这样，但是讲义里又明确提到了“值变化”这一概念，所以我有点疑惑
![image](https://user-images.githubusercontent.com/57026939/227230067-f1598655-d1ad-4021-9871-785fcae22972.png)

**Comment by Googol2002** [comment]
这应该是我没有严格按照讲义来做。
按照讲义做会为这个debugger引入一些内部状态，需要记录上一个时刻表达式的值，我的这个版本是一个纯反应式的debugger。
按照讲义肯定也是可以的。

**Comment by hululu-lzb** [comment]
嗯嗯，那我明白了，感谢！！！

**Comment by Googol2002** [comment]
学习顺利！

**Comment by hululu-lzb** [comment]
The author is very nice
