### ISSUE TITLE
对difftest的dut.c的改动

### ISSUE THREAD

**Issue by nidianwo** [Googol2002/NJU-ICS2021-PA#4]
我发现你对nemu/src/cpu/difftest/dut.c的一个地方做出改动。
`
  //TODO: 这里npc原先是pc的，但是看起来实在不正确
  checkregs(&ref_r, npc);`
这里似乎不应该变动，不改动时运行出错是因为你对nemu/src/isa/riscv32/difftest/dut.c的bool isa_difftest_checkregs(CPU_state *ref_r, vaddr_t pc)函数的实现有错误。在比较pc值时，你应该比较的是ref的pc和cpu此时的pc，而不是这个函数传递的那个参数pc，根据ics2021的文档api的定义。https://nju-projectn.github.io/ics-pa-gitbook/ics2021/nemu-isa-api.html
> NEMU作为DUT时使用
bool isa_difftest_checkregs(CPU_state *ref_r, vaddr_t pc);
检查当前的寄存器状态是否与ref_r相同, 其中pc为cpu.pc的上一条动态指令的PC, 即cpu.pc的旧值. 如果状态相同, 则返回true, 否则返回false.
因此这个pc是用来提示报错信息的。我认为bool isa_difftest_checkregs(CPU_state *ref_r, vaddr_t pc)函数的实现应该如下：
`bool isa_difftest_checkregs(CPU_state *ref_r, vaddr_t pc) {
  for (int i = 0; i < 32; ++i){
    if (ref_r->gpr[i]._32 != cpu.gpr[i]._32){
      error_finfo();
      Log("对于[%s]寄存器, expceted %x, but got %x.", regs[i], ref_r->gpr[i]._32, cpu.gpr[i]._32);
      Assert(ref_r->pc == cpu.pc, "PC expected %x but got %x", ref_r->pc, cpu.pc);
      return false;
    }
  }

  if (ref_r->pc == cpu.pc){
    return true;
  }else {
    error_finfo();
    Log("PC expected %x but got %x", ref_r->pc, cpu.pc);
    return false;
  }
}`

**Comment by Googol2002** [comment]
我对这个项目具体实现的记忆有些模糊了，但看起来你说的应该是有道理的。
不过，为了稳妥起见，我不再修改这个项目代码了。
我会把你的Issue置顶，希望可以帮到其他有同样困惑的人。
